version: "3.9"

services:
  web:
    build: .
    container_name: todo-api
    ports:
      - "8000:8000"
    volumes:
    - .:/code
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todo
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: